In [4]:
list_v2 = [{1:'홍길동1',2:'홍길동2'},
           {1:'이순신1',2:'이순신2'},
           {1:'강감찬1',2:'강감찬2'}]

# print(list_v2)

for d in list_v2:
    print(d)
    for k in d:
        print("key:{}/ value:{}".format(k,d[k]))

{1: '홍길동1', 2: '홍길동2'}
key:1/ value:홍길동1
key:2/ value:홍길동2
{1: '이순신1', 2: '이순신2'}
key:1/ value:이순신1
key:2/ value:이순신2
{1: '강감찬1', 2: '강감찬2'}
key:1/ value:강감찬1
key:2/ value:강감찬2

In [5]:
# for 문으로 실행할 수 있는 4가지 -> 1.딕셔너리, 2.리스트 3. 튜플 4. 문자열
# 여러개를 넣을 수 있는 값들 -> for문 가능, index number 부여 가능
# for k in d.keys(); 형태로 딕셔너리 접근

In [21]:
# "강감찬1"값이 있는 key와 value값만 출력해 주세요
# 답 : key : 1 / value : 강감찬1
# d.keys()
# k=2 -> d[2] -> "강감찬1"

for d in list_v2:
    print(d)
    for k in d.keys():
        if d[k] == "강감찬1":
            print(k, " : ",d[k])

{1: '홍길동1', 2: '홍길동2'}
{1: '이순신1', 2: '이순신2'}
{1: '강감찬1', 2: '강감찬2'}
1  :  강감찬1

In [23]:
# "강감찬1"이라는 값이 포함되어 있는 부분의 딕셔너리의 전체 key와 value를 출력하기
# 답 :
# key : 1 / value : 강감찬1
# key : 2 / value : 강감찬2

for d in list_v2:
    print(d.values())
    
"aaa" in ["aaac","bbb","ccc"]

dict_values(['홍길동1', '홍길동2'])
dict_values(['이순신1', '이순신2'])
dict_values(['강감찬1', '강감찬2'])

False

In [115]:
# list_v2안에 강감찬1의 값이 있으면 true 없으면 false
for d in list_v2:
    if "강감찬1" in d.values() :
        # print(d.values(), "강감찬1" in d.values())
        for k in d.keys():
            print(k, " : ",d[k])

1  :  강감찬1
2  :  강감찬2

In [113]:
### [문제] key값이 1~100까지, value값이 홍길동1~홍길동100까지의 값 생성하기
# {1:"홍길동1", 2:"홍길동2",~100:"홍길동100"}
# 딕셔너리 변수명 : dict_100
# 딕셔너리는 키값이 다르면 계속 추가된다.

In [114]:
dict_100 = {}
for i in range(1,101, 1):
    dict_100[i] = "홍길동{}".format(i)
print(dict_100)

{1: '홍길동1', 2: '홍길동2', 3: '홍길동3', 4: '홍길동4', 5: '홍길동5', 6: '홍길동6', 7: '홍길동7', 8: '홍길동8', 9: '홍길동9', 10: '홍길동10', 11: '홍길동11', 12: '홍길동12', 13: '홍길동13', 14: '홍길동14', 15: '홍길동15', 16: '홍길동16', 17: '홍길동17', 18: '홍길동18', 19: '홍길동19', 20: '홍길동20', 21: '홍길동21', 22: '홍길동22', 23: '홍길동23', 24: '홍길동24', 25: '홍길동25', 26: '홍길동26', 27: '홍길동27', 28: '홍길동28', 29: '홍길동29', 30: '홍길동30', 31: '홍길동31', 32: '홍길동32', 33: '홍길동33', 34: '홍길동34', 35: '홍길동35', 36: '홍길동36', 37: '홍길동37', 38: '홍길동38', 39: '홍길동39', 40: '홍길동40', 41: '홍길동41', 42: '홍길동42', 43: '홍길동43', 44: '홍길동44', 45: '홍길동45', 46: '홍길동46', 47: '홍길동47', 48: '홍길동48', 49: '홍길동49', 50: '홍길동50', 51: '홍길동51', 52: '홍길동52', 53: '홍길동53', 54: '홍길동54', 55: '홍길동55', 56: '홍길동56', 57: '홍길동57', 58: '홍길동58', 59: '홍길동59', 60: '홍길동60', 61: '홍길동61', 62: '홍길동62', 63: '홍길동63', 64: '홍길동64', 65: '홍길동65', 66: '홍길동66', 67: '홍길동67', 68: '홍길동68', 69: '홍길동69', 70: '홍길동70', 71: '홍길동71', 72: '홍길동72', 73: '홍길동73', 74: '홍길동74', 75: '홍길동75', 76: '홍길동76', 77: '홍길동77', 78: '홍길동78', 79: '홍길동79', 80: '홍길동80', 81: '홍길동81', 82: '홍길동82', 83: '홍길동83', 84: '홍길동84', 85: '홍길동85', 86: '홍길동86', 87: '홍길동87', 88: '홍길동88', 89: '홍길동89', 90: '홍길동90', 91: '홍길동91', 92: '홍길동92', 93: '홍길동93', 94: '홍길동94', 95: '홍길동95', 96: '홍길동96', 97: '홍길동97', 98: '홍길동98', 99: '홍길동99', 100: '홍길동100'}

In [107]:
dict_100

{1: '홍길동1',
 2: '홍길동2',
 3: '홍길동3',
 4: '홍길동4',
 5: '홍길동5',
 6: '홍길동6',
 7: '홍길동7',
 8: '홍길동8',
 9: '홍길동9',
 10: '홍길동10',
 11: '홍길동11',
 12: '홍길동12',
 13: '홍길동13',
 14: '홍길동14',
 15: '홍길동15',
 16: '홍길동16',
 17: '홍길동17',
 18: '홍길동18',
 19: '홍길동19',
 20: '홍길동20',
 21: '홍길동21',
 22: '홍길동22',
 23: '홍길동23',
 24: '홍길동24',
 25: '홍길동25',
 26: '홍길동26',
 27: '홍길동27',
 28: '홍길동28',
 29: '홍길동29',
 30: '홍길동30',
 31: '홍길동31',
 32: '홍길동32',
 33: '홍길동33',
 34: '홍길동34',
 35: '홍길동35',
 36: '홍길동36',
 37: '홍길동37',
 38: '홍길동38',
 39: '홍길동39',
 40: '홍길동40',
 41: '홍길동41',
 42: '홍길동42',
 43: '홍길동43',
 44: '홍길동44',
 45: '홍길동45',
 46: '홍길동46',
 47: '홍길동47',
 48: '홍길동48',
 49: '홍길동49',
 50: '홍길동50',
 51: '홍길동51',
 52: '홍길동52',
 53: '홍길동53',
 54: '홍길동54',
 55: '홍길동55',
 56: '홍길동56',
 57: '홍길동57',
 58: '홍길동58',
 59: '홍길동59',
 60: '홍길동60',
 61: '홍길동61',
 62: '홍길동62',
 63: '홍길동63',
 64: '홍길동64',
 65: '홍길동65',
 66: '홍길동66',
 67: '홍길동67',
 68: '홍길동68',
 69: '홍길동69',
 70: '홍길동70',
 71: '홍길동71',
 72: '홍길동72',
 73: '홍길동73',
 74: '홍길동74',
 75: '홍길동75',
 76: '홍길동76',
 77: '홍길동77',
 78: '홍길동78',
 79: '홍길동79',
 80: '홍길동80',
 81: '홍길동81',
 82: '홍길동82',
 83: '홍길동83',
 84: '홍길동84',
 85: '홍길동85',
 86: '홍길동86',
 87: '홍길동87',
 88: '홍길동88',
 89: '홍길동89',
 90: '홍길동90',
 91: '홍길동91',
 92: '홍길동92',
 93: '홍길동93',
 94: '홍길동94',
 95: '홍길동95',
 96: '홍길동96',
 97: '홍길동97',
 98: '홍길동98',
 99: '홍길동99',
 100: '홍길동100'}

In [111]:
### 1부터 100까지의 합의 결과를 출력해 주세요
# 1+2+3+4...+100 = ?
i=1
sum=0
for i in range(1,101,1):
    sum += i
print(sum)

5050